logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC

server:
  adminConnectors:
    -
      port: 18001
      type: http
  adminContextPath: /admin
  applicationConnectors:
    -
      port: 18000
      type: http
  rootPath: /auth/*
  type: default

dbConfig:
  driverClass: com.mysql.jdbc.Driver&
  user: root
  password: root
  url: jdbc:mysql://127.0.0.1:3306/meetup?autoReconnect=true
  properties:
   hibernate.dialect: org.hibernate.dialect.MySQLDialect
   c3p0.acquireIncrement: 5
   c3p0.initialPoolSize: 5
   c3p0.minPoolSize: 10
   c3p0.maxPoolSize: 50
   c3p0.maxIdleTime: 300
   c3p0.maxStatements: 500
   c3p0.idleConnectionTestPeriod: 30